### PR TITLE
finnFeil_main.c

### PR DESCRIPTION
**Pull request by hansrobl**
Finn 5 feil!?!

### CODE REVIEW

**Review by bardust — CHANGES_REQUESTED** [review]
Missing # line 19
Changed to 8 bit line 30
Changed to 3 line 44
Changed bit to spit line 60
Changed to 0xFF line 69

Please change back and merge :)

**Review by bardust — APPROVED** [review]
All is well. Spit is nice.

**Comment by hansrobl** [comment]
Do you think its fine?

**Comment by bardust** [comment]
Changed to spit and higher LED value, MORE LEDs!!!!

**Pull request merged**
